# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=30)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='unknown', max_length=30)),
                ('section_id', models.IntegerField(blank=True)),
                ('categories', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('last_scan', models.DateTimeField(blank=True, verbose_name='last scanned')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('page_views', models.IntegerField(blank=True)),
                ('page_views_unique', models.IntegerField(blank=True)),
                ('average_time', models.CharField(blank=True, max_length=10)),
                ('entrances', models.IntegerField(blank=True)),
                ('bounce_rate', models.CharField(blank=True, max_length=10)),
                ('exit_percent', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='conversion',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_destination_set', to='pages.Page'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_source_set', to='pages.Page'),
        ),
    ]
