# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
