# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160628_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='entrances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_views_unique',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
