# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160628_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='entrances',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_views',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_views_unique',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='section_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
