# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_tag'),
        ('pages', '0008_pagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='default_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
