# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_default_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contacts',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.CharField(choices=[('bloomington.in.gov/alpha', 'Alpha (destination)'), ('bloomington.in.gov', 'Current (source)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
