"""
Django settings for converter project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f#8e!d%_t8#reaegdai6#cfg$89nsf31$*w+978&$*pooc%(6q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'pages.apps.PagesConfig',
    'topics.apps.TopicsConfig',
    'departments.apps.DepartmentsConfig',
    'navigation',
    'widget_type',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'converter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'converter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    ## 'default': {
    ##     'ENGINE': 'django.db.backends.sqlite3',
    ##     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    ## }

    ## 'default': {
    ##     'ENGINE': 'django.db.backends.mysql',

    ##     #these should be specified / set in mysql.cnf
    ##     #(which should make it easier to ignore them in version control)
    ##     'NAME' : 'migrations',

    ##     'USER' : 'mig-user',
    ##     'PASSWORD' : 'mig-password',
    ##     #'USER' : 'root',
    ##     #'PASSWORD' : 'my-secret-pw',

    ##     'PORT': '3306',
    ##     #should be whatever name is linked
    ##     #'HOST': 'db',
    ##     'HOST': '172.17.0.2',

    ##     # TODO:
    ##     # I would really like to use this setting,
    ##     # but having difficulty getting it to work
    ##     # moving on with direct settings for now
    ##     # via:
    ##     # https://docs.djangoproject.com/en/1.9/ref/databases/#connecting-to-the-database
    ##     #'OPTIONS': {
    ##     #    'read_default_file': 'mysql.cnf',
    ##     #},
    ## }

    'default': {
        'ENGINE': 'django.db.backends.mysql',

        #these should be specified / set in mysql.cnf
        #(which should make it easier to ignore them in version control)
        'NAME' : 'example_db',

        'USER' : 'example_user',
        'PASSWORD' : 'similarly-secure-password',

        #'PORT': '3306',
        #should be whatever name is linked
        #'HOST': 'db',
        #'HOST': '172.17.0.2',

        # TODO:
        # I would really like to use this setting,
        # but having difficulty getting it to work
        # moving on with direct settings for now
        # via:
        # https://docs.djangoproject.com/en/1.9/ref/databases/#connecting-to-the-database
        #'OPTIONS': {
        #    'read_default_file': 'mysql.cnf',
        #},
    }


}    

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
